config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  resources :movies
  get '/movies' => 'movies#index'
  get '/movies/:id' => 'movies#show'
  
  get 'movies/new' => 'movies#new', as: :add_movie
  post 'movies' => 'movies#create'
  delete '/movies/:id' => 'movies#destroy'

  resources :orders
  get '/orders' => 'orders#index'
  get '/orders/new' => 'orders#new'

  post 'orders' => 'orders#create'

  resources :showtimes
  get '/showtimes/:id' => 'showtimes#show'
  get 'showtimes/new' => 'showtimes#new', as: :add_showtime
  post 'showtimes' => 'showtimes#create'

 

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	validates :title, :release_year, :plot, :theater_id, presence: true
	has_many :showtimes, dependent: :destroy

end

app/models/order.rb
class Order < ActiveRecord::Base
    #attr_accessible :movie_id, :showtime_id

	belongs_to :showtime
	has_one :movie, through: :showtime

	validates :first_name, :last_name, :age, :email, :credit_card, :expiration, :showtime_id, :movie_id, :order_quantity, presence: true
	validate :order_quantity, if: :orders_sold_out?
	validate :age, if: :age_restriction?
    
    # the sum only sum up the previous orders, without the most current one.
  
    def order_total
      if self.showtime_id.present?
         my_order = Order.where(showtime_id: self.showtime_id)
         #my_order_total = my_order.group(:showtime_id).sum(:order_quantity) 
         my_order_total = my_order.sum(:order_quantity) + self.order_quantity # works
         #my_order_total = my_order.pluck(:order_quantity).inject(:+) + self.order_quantity
         #total = my_order.map {|o| o['order_quantity']}.reduce(0, :+)
         # total = my_order.inject(0) { |sum, self.order_quantity| sum + self.order_quantity }
         puts "all-orders" * 20
         puts my_order_total
         puts self
         puts "showid" * 50
         puts self.showtime_id # get the showtime_id for new order.
         return my_order_total 
      else
         puts "id is nil"
      end
    end
     

    # find the theater seats capacity:
    def order_limit
        if self.showtime_id.present?
            puts "showid" * 50
            showing = self.showtime_id.to_i
            puts showing
            show_room = Showtime.find(showing).theater_id.to_i
            puts show_room
            available_seats = Theater.find(show_room).seats
            puts available_seats 
            return available_seats
        else
          puts "id is nil."
        end 
    end 

    def orders_sold_out?
      if self.showtime_id.present?
      	if order_total > order_limit.to_i
            puts "$total" * 50
            puts order_total
      		  errors.add(:order_quantity, "All seats are sold out for this movie.")
        else
            puts "Order created."
      	end 
      else 
        puts 'id is nil'
      end 
    end 
  
    def age_restriction?
    	user_age = self.age 
        if user_age != nil
         if user_age <= 18
    	  errors.add(:age, "You must be 18 or older to make a purchase.")
         end 
        end
    end 
end

app/models/showtime.rb
class Showtime < ActiveRecord::Base
	has_many :orders, dependent: :destroy
	belongs_to :theater
	belongs_to :movie

	validates :month, :date, :hour, :year, :movie_id, :theater_id, presence: true
end

app/models/theater.rb
class Theater < ActiveRecord::Base
	has_many :showtimes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	def index
		@movies = Movie.all
	end 

	def show
		@movie = Movie.find(params[:id])
		@showtimes = @movie.showtimes
	end 

	def new
		@movie = Movie.new
		#2.times {@movie.showtimes.build}
	end 

	def create
		@movie = Movie.new(movie_params)
		if @movie.save
			redirect_to '/movies'
		else
			render 'movies/new'
		end 
	end 

	def destroy
		@movie = Movie.find(params[:id])
		@movie.destroy
		redirect_to movies_path
	end 

	private

	def movie_params
		params.require(:movie).permit(:title, :image, :release_year, :plot, :theater_id, :showtime_id)
	end 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	#attr_accessor :showtime_id, :movie_id
	def new
		@order = Order.new
		# @showtime = Showtime.find(params[:id])
		# @movie_id = @showtime.movie_id
	end 

	def index
		@orders = Order.all
	end 
    
	def create
		@order = Order.new(order_params)
		# @order.showtime_id = params[:order][:showtime_id]
		# @order.first_name = params[:order][:first_name]
		if @order.save
			puts "Debug information"
		   flash[:notice] = "Thank you for your order."
		   redirect_to '/movies'
		else 
           render  'new'
        end 
	end 

	def destroy
		@order = Order.find(params[:id])
		@order.destroy
		redirect_to orders_path
	end 

	private

	def order_params
		params.require(:order).permit(:age, :first_name, :last_name, :email, :credit_card, :expiration, :order_quantity, :movie_id, :showtime_id)
	end 
end

app/controllers/showtimes_controller.rb
class ShowtimesController < ApplicationController
	def show
		@showtime = Showtime.find(params[:id])
	end 
   
    def new
    	@showtime = Showtime.new
    end 
    
	def create
		@showtime = Showtime.new(showtime_params)
		if @showtime.save
			puts "Debug information"
		   
		   redirect_to '/movies'
		else 
           render  '/showtimes/new'
        end 
	end 

	private

	def showtime_params
		params.require(:showtime).permit(:month, :date, :hour, :year, :movie_id, :theater_id)
	end 
end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/showtimes_helper.rb
module ShowtimesHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper

	
end

app/views/layouts/_footer.html.erb
<div class="footer">
      <div class="container">
        <br>
        <div class="col-md-4">
          <ul>
            <h3>About</h3>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Team</a></li>
            <li><a href="#">Jobs</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <ul>
            <h3>Support</h3>
            <li><a href="#">Help Center</a></li>
            <li><a href="#">Get Started</a></li>  
            <li><a href="#">Contact Us</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <ul>
            <h3>Community</h3>
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Google+</a></li>
          </ul>
        </div>
      </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar ">
  <div >
    <nav>
      <ul class="nav nav-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Now Playing", root_path %></li>
        <li><%= link_to "Admin", '/orders' %>
        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SifiRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
   <%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/index.html.erb
<div class="hero">
  <div class="container">
    <h2>Black Theater</h2>
    <p>Our special effects theaters offer you the best movie experiences. </p>
    <a href="#">Read More</a>
  </div>
</div>
<br>
<br>
<div class="main container">
  <div>
    <div>
        <% @movies.each do |movie| %>
        <div class="actor col-xs-2">
          <div><%= image_tag movie.image %></div>
          <h3><%= movie.title %></h3>
          <p><%= movie.release_year %></p>
          <p><button class="btn btn-default"><%= link_to "Showtimes", movie_path(movie) %></button></p>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<div class="add-movie">
  <h2>Add Movies</h2>
  <br>
		<%= form_for(@movie) do |f| %>
		<%= render 'shared/movie_error_messages' %>
		<br>
		<ul>
		  <%= f.label :image %>
		  <%= f.text_field :image, :placeholder => "Image url", class:"form-control" %>
          <%= f.label :title %>
		  <%= f.text_field :title, :placeholder => "Movie title", class:"form-control" %>
		  <%= f.label :release_year %>
		  <%= f.text_field :release_year, :placeholder => "Release Year", class:"form-control" %>

		  <%= f.label :plot %>
		  <%= f.text_field :plot, :placeholder => "Plot", class:"form-control" %>

		  <%= f.label :theater_id %>
		  <%= f.text_field :theater_id, :placeholder => "Theater ID", class:"form-control" %>

          
		</ul>
		<br>
		<%= f.submit "Add Movie", class:"btn btn-primary" %>
	<% end %>
</div>

app/views/movies/show.html.erb
<div class="main actor-show">
  <div class="container">
    <!-- Display an moive's info here -->
    <div class="actor">
      <%= image_tag @movie.image %>
      <div class="info">
        <h3 class="actor-name"><%= @movie.title %></h3>
        <br>
        <p> <%= @movie.plot %></p>
        <p> Theater: <%= @movie.theater_id %></p>
        <button class="btn btn-default"> <%= link_to 'Delete Movie', @movie, method: :delete, data: {confirm: "You sure?"} %></button>

        <h3 class="actor-bio"> Showtime: </h3>
          <% @showtimes.each do |showing| %>
          <br>
          <!--the showtime id shows in the url -->  
           <p class="actor-name">
             <%= showing.hour %> <span>=></span> 
             <button class="btn btn-default">
              <%= link_to('Buy Ticket', controller: 'orders', action: 'new', showtime_id: showing) %>
             </button>
           </p>
         <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<br>
<div class="row">
  <div class="container">
    <h2> Order Histroy </h2>
    <br>

    <% @orders.each do |order| %>
      <table id="table-info">

        <tr>
          <td>Age: <%= order.age %></td>
          <td>Name: <%= order.first_name %> <%= order.last_name %></td> 
          <td>Email: <%= order.email %></td> 
          <td>Credit Card: <%= order.credit_card %></td>
          <td>Expiration: <%= order.expiration %></td>
          <td>Quantity: <%= order.order_quantity %></td>
          <td><%= link_to 'Delete', order, method: :delete, data: {confirm: "You sure?"} %></td>
       </tr>
    </table>
    <% end %>
    <div>
    <!--Add movie-->
    <h2>Add Movies</h2>
    <button class="btn btn-default"><%= link_to "Add Movie", add_movie_path(@movie) %></button>
    </div>
    <br>
    <div>
      <button class="btn btn-default"><%= link_to "Add Showtime", add_showtime_path(@showtime) %></button>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<br>
<div class="container">
      <div>
        <h2>Buy Ticket</h2>
        <br>
        <!-- order form  -->
        <%= form_for(@order) do |f| %>
        <ul id="order-form">
         <%= render 'shared/error_messages' %>
         <%= f.label :age %>
         <%= f.text_field :age, :placeholder => "Your age" %>
         <%= f.label :first_name %> 
         <%= f.text_field :first_name, :placeholder => "First name" %>
         <%= f.label :last_name %>
         <%= f.text_field :last_name, :placeholder => "Last name" %>
          <%= f.label :email %>
          <%= f.text_field :email, :placeholder => "Email" %>
          <%= f.label :credit_card %>
          <%= f.text_field :credit_card, :placeholder => "Credit card number" %>
          <%= f.label :expiration %>
          <%= f.text_field :expiration, :placeholder => "expiration date" %>
          <%= f.label :order_quantity %>
          <%= f.text_field :order_quantity, :placeholder => "Quantity" %>
          <!--https://github.com/ryanb/nested_form-->
          <!--not showing the movie and showtime id, it is hidden, how to get the showtime id before the form is submitted??, need a model action?<%#= f.hidden_field :movie_id, value: params[:movie_id] %>-->
          
          <%= f.label :movie_id %>
          <%= f.text_field :movie_id, :value => params[:movie_id] || @order.movie_id %>

          <%= f.label :showtime_id %>
          <%= f.text_field :showtime_id, :value => params[:showtime_id] || @order.showtime_id %>


         <br>
          <%= f.submit "Checkout", :class => "btn btn-primary" %> 
        </ul>
        <% end %> 
        <br>
      </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @order.errors.any? %>

  	<div class="alert alert-danger">
  		The form contains <%= pluralize(@order.errors.count, "error") %>.
  	</div>
  		
  		<% @order.errors.full_messages.each do |msg| %>
  	<div id="error_details">
  		<li class="order-error-msg"><%= msg %></li>
  	</div>
  
<% end %>
<% end %>

<br>

app/views/shared/_movie_error_messages.html.erb
<% if @movie.errors.any? %>
  
  	<div class="alert alert-danger">
  		The form contains <%= pluralize(@movie.errors.count, "error") %>.
  	</div>
  	
	<% @movie.errors.full_messages.each do |msg| %>
	<li class="movie-error"><%= msg %></li>

    <% end %>
<% end %>

app/views/shared/_showtime_error_messages.html.erb
<% if @showtime.errors.any? %>
  
  	<div class="alert alert-danger">
  		The form contains <%= pluralize(@showtime.errors.count, "error") %>.
  	</div>
  	
  	<% @showtime.errors.full_messages.each do |msg| %>
  	<li class="movie-error"><%= msg %></li>
 
    <% end %>
<% end %>

app/views/showtimes/new.html.erb
<div class="add-movie">
  <h2>Add Showtimes</h2>
  <br>
		<%= form_for(@showtime) do |f| %>
		<%= render 'shared/showtime_error_messages' %>
		<br>
		<ul>
		  <%= f.label :month %>
		  <%= f.text_field :month, :placeholder => "Month", class:"form-control" %>
          <%= f.label :date %>
		  <%= f.text_field :date, :placeholder => "Date", class:"form-control" %>
		  <%= f.label :hour %>
		  <%= f.text_field :hour, :placeholder => "Hour", class:"form-control" %>

		  <%= f.label :year %>
		  <%= f.text_field :year, :placeholder => "Year", class:"form-control" %>

		  <%= f.label :movie_id %>
		  <%= f.text_field :movie_id, :placeholder => "Moive ID", class:"form-control" %>
         <br>
		  <%= f.label :theater_id %>
		  <%= f.text_field :theater_id, :placeholder => "Theater ID", class:"form-control" %>
		  <br>
		</ul>
		 
		  <!--
		 <div>
		  <%= select_month(Time.now) %>
          <%= select_day(Time.now) %>
          <%= select_hour(Time.now) %>
          <%= select_year(2016) %>
        </div>
        -->
        <br>
		<div>
		  <%= f.submit "Add Showtime", class:"btn btn-primary" %>
		</div>
	<% end %>
</div>